port: 7890
socks-port: 7891
mixed-port: 7893
allow-lan: true
mode: Rule
log-level: info
external-controller: 0.0.0.0:9090
dns:
  enable: true # 是否启用dns false
  ipv6: false
  #listen: 0.0.0.0:53
  enhanced-mode: redir-host # 模式：redir-host或fake-ip
  fake-ip-range: 198.18.0.1/16 #
  fake-ip-filter: # fake ip 白名单列表，如果你不知道这个参数的作用，请勿修改
    - '*.lan'
    - '*.dev'
    - '*.local'
    - '*.test'
    - localhost.ptlogin2.qq.com
  default-nameserver:
     - 114.114.114.114
     - 8.8.8.8
  nameserver:
     - https://doh.pub/dns-query
     - https://dns.alidns.com/dns-query
  fallback:
     - https://dns.google/dns-query
     - tls://dns.google
     - https://dns.adguard.com/dns-query
     - https://dns.cloudflare.com/dns-query
  fallback-filter:
    geoip: true # 默认
    ipcidr: # 在这个网段内的 IP 地址会被考虑为被污染的 IP
       - 240.0.0.0/4
       - 0.0.0.0/32
       - 127.0.0.1/32
